apiVersion: v1
kind: Service
metadata:
  name: ovc-backend-service-nodeport
  namespace: ovc-infra
spec:
  type: NodePort
  selector: { app: ovc-backend }
  ports: [{ name: http, port: 8000, targetPort: 8000, nodePort: 30800 }]
